configured_endpoints: 95
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nextbillion-ai%2Fnextbillion-sdk-829b0241cf91557ffa78f1cb0afebfd48cb7003873d839140c4f806aecdd43af.yml
openapi_spec_hash: ddafb987b7b2c2c42ccdb59d65ab007a
config_hash: bc249c8c9aa0b54785cf426c3d5662af
